# Generated by Django 3.2 on 2021-06-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('keywords', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=15)),
            ],
        ),
    ]
